version: "3"
services:
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}
    volumes:
      - ./server/src:/srv/app/toolbox-server/src
    command: npm  run-script build

  client:
    build: ./client
    stdin_open: true
    expose:
      - ${REACT_APP_PORT}
    environment:
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/srv/app/toolbox-client/src
      - ./client/public:/srv/app/toolbox-client/public
    links:
      - server
    command: npm start
